feat: Fixed data structure
tazama-lf/tms-service pull request #188
Opened 2024-07-01 05:13 UTC by JeanPierreNell

In Relation to https://github.com/frmscoe/tms-service/issues/177

2024-07-01 10:51 UTC, Lenbkr approved these changes, later dismissed

2024-07-01 11:53 UTC, Sandy-at-Tazama approved these changes

2024-07-01 13:43 UTC, Sandy-at-Tazama requested changes
Documentation to be updated for tms-service for this change

2024-07-02 07:16 UTC, Justus-at-Tazama commented
![image](https://github.com/frmscoe/tms-service/assets/123470803/31c31f09-0be7-44c2-b1e4-1182c9811b72)
End-to-end test with Rule-901 successful

2024-07-02 12:10 UTC, Lenbkr approved these changes

2024-07-02 14:17 UTC, Justus-at-Tazama approved these changes

2024-07-02 14:19 UTC, Sandy-at-Tazama approved these changes

2024-07-02 14:20 UTC, merged