Database environmental config update and refactoring of library use
tazama-lf/tms-service pull request #191
Opened 2024-07-04 13:53 UTC by Lenbkr

# SPDX-License-Identifier: Apache-2.0

## What did we change?

## Why are we doing this?

## How was it tested?
- [x] Locally
- [x] Development Environment
- [ ] Not needed, changes very basic
- [x] Husky successfully run
- [ ] Unit tests passing and Documentation done

2024-07-05 11:41 UTC, Justus-at-Tazama requested changes
There are quite a few changes in the code that appears to be housekeeping/cleanup and I'm not too sure that I can comment on the changes without understanding the intent. The PR is a bit, uhm, lacking in this area. Can we please update the PR to also summarize the changes at a high level?

2024-07-05 11:41 UTC, Justus-at-Tazama commented on README.md
> +Currently, it accepts ISO20022 Pain001.001.11 message, pain.013 message, pacs.002.001.12 and pacs.008.001.10. For more information click [here](https://github.com/frmscoe/docs/blob/dev/Knowledge-Arti
Somewhat inconsistent naming of the different ISO20022 messages here. Recommend:

"Currently, the TMS API is able to accept ISO20022 pain.001.001.11, pain.013.001.09, pacs.002.001.12 and pacs.008.001.10 messages. Depending on the configuration of the TMS API service via the `QUOTING` environment variable, the pain.001 and pain.013 messages may be excluded (`QUOTING=FALSE`)."

2024-07-08 10:22 UTC, rtkay123 approved these changes

2024-07-08 13:01 UTC, Justus-at-Tazama approved these changes

2024-07-08 13:02 UTC, merged