ci: sync workflows from central-workflows
tazama-lf/tms-service pull request #200
Opened 2024-07-10 14:46 UTC by vorsterk

This PR syncs workflows from the central-workflows repository. Signed-off-by: Kyle Vorster <93905748+vorsterk@users.noreply.github.com>

2024-07-10 17:18 UTC, scott45 approved these changes

2024-07-11 07:19 UTC, rtkay123 commented
@cshezi Please take a look at the `bench` workflow. Will that work? All I see is some git commands. Where is the actual benchmark happening?

2024-07-11 07:31 UTC, cshezi requested changes

2024-07-11 07:31 UTC, cshezi commented on .github/workflows/bench.yaml
> +          cd ${{ env.REPO_NAME }}
Please remove this bench yaml file if the integration tests are being removed due to that this job depends on the integration test to store its result to its relative branch as a temp file and this job moves or publishes the bench of the PR when merged this job is expected to move the result to the main branch of performance-benchmark

2024-07-11 09:48 UTC, closed without merging